# Generated by Django 5.1.3 on 2024-11-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='subtitel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
