# Generated by Django 5.1.3 on 2024-11-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_subtitel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='subtitel',
        ),
        migrations.AddField(
            model_name='homepage',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Підзаголовок'),
        ),
    ]
